const modules = [
    { name: "Algo", coef: 5, hasTP: true, hasTD: true },
    { name: "Algèbre", coef: 3, hasTP: false, hasTD: true },
    { name: "Analyse", coef: 5, hasTP: false, hasTD: true },
    { name: "STRM", coef: 4, hasTP: false, hasTD: true },
    { name: "Français", coef: 1, hasTP: false, hasTD: false },
    { name: "Bureautique", coef: 2, hasTP: false, hasTD: false },
    { name: "Physique", coef: 2, hasTP: false, hasTD: true },
    { name: "SE", coef: 3, hasTP: true, hasTD: false }
];

const container = document.getElementById("modulesContainer");

// Generate input fields dynamically
modules.forEach((module, index) => {
    let html = `<div class="module">
        <h3>${module.name} (Coef: ${module.coef}) - <span id="avg${index}">--</span></h3>
        ${module.hasTP ? `<label>TP: <input type="number" min="0" max="20" id="tp${index}"></label>` : ""}
        ${module.hasTD ? `<label>TD: <input type="number" min="0" max="20" id="td${index}"></label>` : ""}
        <label>Exam: <input type="number" min="0" max="20" id="exam${index}"></label>
    </div>`;
    container.innerHTML += html;
});

function calculateAverages() {
    let totalWeightedSum = 0, totalCoef = 0;

    modules.forEach((module, index) => {
        let tp = module.hasTP ? parseFloat(document.getElementById(`tp${index}`).value) || 0 : 0;
        let td = module.hasTD ? parseFloat(document.getElementById(`td${index}`).value) || 0 : 0;
        let exam = parseFloat(document.getElementById(`exam${index}`).value) || 0;

        let moduleAverage = module.hasTP 
            ? (tp * 0.2) + (td * 0.2) + (exam * 0.6) 
            : module.hasTD 
            ? (td * 0.4) + (exam * 0.6) 
            : exam;

        totalWeightedSum += moduleAverage * module.coef;
        totalCoef += module.coef;

        document.getElementById(`avg${index}`).innerText = moduleAverage.toFixed(2);
    });

    let finalAverage = totalWeightedSum / totalCoef;
    document.getElementById("finalAverage").innerText = `Final Average: ${finalAverage.toFixed(2)} / 20`;
}

function downloadPDF() {
    const { jsPDF } = window.jspdf;
    let doc = new jsPDF({
        orientation: "portrait",
        unit: "mm",
        format: "a4"
    });

    let studentName = document.getElementById("studentName").value || "Unknown Student";

    // Header
    doc.setFont("helvetica", "bold");
    doc.setFontSize(18);
    doc.setTextColor(0, 122, 255);
    doc.text("Student Report Card", 105, 20, null, null, "center");

    doc.setFontSize(14);
    doc.setTextColor(0);
    doc.text(`Student Name: ${studentName}`, 20, 30);

    // Table Header
    let y = 45;
    doc.setFontSize(12);
    doc.setFillColor(0, 122, 255);
    doc.setTextColor(255);
    doc.rect(20, y, 170, 10, "F"); // Blue header background
    doc.text("Module", 25, y + 7);
    doc.text("TP", 85, y + 7);
    doc.text("TD", 105, y + 7);
    doc.text("Exam", 125, y + 7);
    doc.text("Average", 145, y + 7);

    // Table Rows
    y += 12;
    doc.setFontSize(10);
    doc.setTextColor(0);
    
    modules.forEach((module, index) => {
        let tp = module.hasTP ? (document.getElementById(`tp${index}`).value || "--") : "--";
        let td = module.hasTD ? (document.getElementById(`td${index}`).value || "--") : "--";
        let exam = document.getElementById(`exam${index}`).value || "--";
        let avg = document.getElementById(`avg${index}`).innerText;

        doc.rect(20, y, 170, 8);
        doc.text(module.name, 25, y + 5);
        doc.text(tp, 90, y + 5);
        doc.text(td, 110, y + 5);
        doc.text(exam, 130, y + 5);
        doc.text(avg, 150, y + 5);
        
        y += 9;
    });

    // Final Average
    doc.setFont("helvetica", "bold");
    doc.setFontSize(12);
    doc.setFillColor(255, 255, 0);
    doc.setTextColor(0);
    doc.rect(20, y, 170, 10, "F");
    doc.text(`Final Average: ${document.getElementById("finalAverage").innerText}`, 25, y + 7);

    // Footer
    doc.setFontSize(10);
    doc.setTextColor(100);
    doc.text("Generated by Yacinz Calculator", 105, 280, null, null, "center");

    doc.save(`${studentName}_Report.pdf`);
        }
